<a href="https://colab.research.google.com/github/PedroIsac564/data_science_aulas/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(1)

1


In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

print(w1)
print(w2)
print(w3)

0.3
0.2
0.5


In [ ]:
#Pesos da equação
w1, w2, w3 = 0.3, 0.2, 0.5

#dados climaticos da regiao A
regiaoA_temp = 22
regiaoA_chuva = 67
regiaoA_umid = 65

#aplicando o modelo
regiaoA_goiaba = regiaoA_temp * w1 + regiaoA_chuva * w2 + regiaoA_umid * w3
print(f"Na região A a produção de {regiaoA_goiaba} toneladas por hectares")

Na região A a produção de 52.5 toneladas por hectares


In [ ]:
RegiaoA = [22, 67, 65]
RegiaoB = [24, 88, 95]
RegiaoC = [17, 134, 50]
RegiaoD = [18, 96, 70]

pesos = [w1, w2, w3]

In [ ]:
# Criando função
def test(a,b):
  print(a+b)
x = "Test"
y = "3"
test(x, y)

Test3


In [ ]:
# Usando zip para juntar listas

nomes = ['Pedro', 'Xandão', 'Pelé']
idade = [18, 36, 85]

#Combinando lista
lista_completa = list(zip(nomes, idade))
print(lista_completa)

[('Pedro', 18), ('Xandão', 18), ('Pelé', 49)]


In [ ]:
RegiaoA = [22, 67, 65]
RegiaoB = [24, 88, 95]
RegiaoC = [17, 134, 50]
RegiaoD = [18, 96, 70]

pesos = [w1, w2, w3]

def producao_goiaba(regiao, pesos):
  result = 0
  for x, w in zip(regiao, pesos):
    result += x * w
  return result

print(producao_goiaba(RegiaoA, pesos))

52.5


In [ ]:
import numpy as np

RegiaoA = np.array([22, 67, 65])

print(type(RegiaoA))

pesos = np.array([w1, w2, w3])

print(type(pesos))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
reg_a = np.dot(RegiaoA, pesos)
print('Regiao A: {}'.format(reg_a))

In [ ]:
# Lista em Python
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))

# vetor em Numpy
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))
result = 0
for x1, x2 in zip(arr1, arr2):
  result += x1 * x2
print(result)

4666663666667000000
CPU times: user 516 ms, sys: 240 ms, total: 756 ms
Wall time: 765 ms


In [ ]:
%time
arr1 = list(range(2000000))
arr2 = list(range(1000000, 3000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)
print(np.dot(arr1_np, arr2_np))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 8.58 µs
4666663666667000000


In [ ]:
#criando matriz usando numpay array
dados_climaticos = np.array ([[22, 67, 65], [24, 88, 95], [17, 134, 50], [18, 96, 70]])

print(dados_climaticos)

[[ 22  67  65]
 [ 24  88  95]
 [ 17 134  50]
 [ 18  96  70]]


In [ ]:
print(dados_climaticos.shape)
print(pesos.shape)

# 3D array
arr3 = np.array([[[11,12,13], [13,1,15]],[[15,16,17], []]])

In [ ]:
print(pesos.dtype)
print('--------')
print(dados_climaticos.dtype)

float64
--------
int64


In [ ]:
np.matmul(dados_climaticos, pesos)

array([52.5, 72.3, 56.9, 59.6])

In [ ]:
dados_climaticos @ pesos

array([52.5, 72.3, 56.9, 59.6])

In [ ]:
#Puxando os dados de uma tabela do exel para criar um array em forma de planilha
import numpy as np
goiaba_csv = np.genfromtxt('/content/goiaba.csv', delimiter = ',')

In [ ]:
goiaba_csv

array([[23., 29., 95.],
       [24., 20., 21.],
       [18., 23., 16.],
       [19., 30., 36.]])

In [ ]:
pesos = np.array([0.4, 0.2, 0.8])

In [ ]:
rendimento = goiaba_csv @ pesos

In [ ]:
rendimento

array([91. , 30.4, 24.6, 42.4])

In [ ]:
# incluir o resultado na região do array
resultado = np.concatenate((goiaba_csv, rendimento.reshape(4, 1)), axis = 1)
resultado

array([[23. , 29. , 95. , 91. ],
       [24. , 20. , 21. , 30.4],
       [18. , 23. , 16. , 24.6],
       [19. , 30. , 36. , 42.4]])

In [ ]:
# Salva uma coluna com todos os resultados e gera um novo arquivo
np.savetxt('goiaba_resultado.csv',
           resultado,
           fmt = '%.2f',
           delimiter = ',',
           header = 'temperatura,precipitação,umidade,rendimento',
           comments='')

In [ ]:
goiaba_resultado_csv = np.genfromtxt('/content/goiaba_resultado.csv', delimiter = ',')

In [ ]:
goiaba_resultado_csv

array([[ nan,  nan,  nan,  nan],
       [23. , 29. , 95. , 91. ],
       [24. , 20. , 21. , 30.4],
       [18. , 23. , 16. , 24.6],
       [19. , 30. , 36. , 42.4]])